// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: homework.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HomeworkService_SubmitHomework_FullMethodName = "/homework.HomeworkService/SubmitHomework"
)

// HomeworkServiceClient is the client API for HomeworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HomeworkServiceClient interface {
	SubmitHomework(ctx context.Context, in *HomeworkRequest, opts ...grpc.CallOption) (*HomeworkResponse, error)
}

type homeworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomeworkServiceClient(cc grpc.ClientConnInterface) HomeworkServiceClient {
	return &homeworkServiceClient{cc}
}

func (c *homeworkServiceClient) SubmitHomework(ctx context.Context, in *HomeworkRequest, opts ...grpc.CallOption) (*HomeworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkResponse)
	err := c.cc.Invoke(ctx, HomeworkService_SubmitHomework_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomeworkServiceServer is the server API for HomeworkService service.
// All implementations must embed UnimplementedHomeworkServiceServer
// for forward compatibility.
type HomeworkServiceServer interface {
	SubmitHomework(context.Context, *HomeworkRequest) (*HomeworkResponse, error)
	mustEmbedUnimplementedHomeworkServiceServer()
}

// UnimplementedHomeworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomeworkServiceServer struct{}

func (UnimplementedHomeworkServiceServer) SubmitHomework(context.Context, *HomeworkRequest) (*HomeworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitHomework not implemented")
}
func (UnimplementedHomeworkServiceServer) mustEmbedUnimplementedHomeworkServiceServer() {}
func (UnimplementedHomeworkServiceServer) testEmbeddedByValue()                         {}

// UnsafeHomeworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomeworkServiceServer will
// result in compilation errors.
type UnsafeHomeworkServiceServer interface {
	mustEmbedUnimplementedHomeworkServiceServer()
}

func RegisterHomeworkServiceServer(s grpc.ServiceRegistrar, srv HomeworkServiceServer) {
	// If the following call pancis, it indicates UnimplementedHomeworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HomeworkService_ServiceDesc, srv)
}

func _HomeworkService_SubmitHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomeworkServiceServer).SubmitHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomeworkService_SubmitHomework_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomeworkServiceServer).SubmitHomework(ctx, req.(*HomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HomeworkService_ServiceDesc is the grpc.ServiceDesc for HomeworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomeworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "homework.HomeworkService",
	HandlerType: (*HomeworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHomework",
			Handler:    _HomeworkService_SubmitHomework_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "homework.proto",
}
