version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-container
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server:
    build:
      context: ./server
    container_name: server-container
    ports:
      - "50051:50051"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ./worker
    container_name: worker-container
    depends_on:
      - rabbitmq

  client:
    build:
      context: ./client
    container_name: client-container
    depends_on:
      - server
